# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/openjdk:11-browsers-legacy

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/postgres:9.4

        working_directory: ~/repo

        environment:
            # Customize the JVM maximum heap limit
            MAVEN_OPTS: -Xmx3200m

        steps:
            - checkout
            - attach_workspace:
                  at: ~/spring-base-bom
            - run: git clone https://github.com/amit-agrawal10-git/spring-base-bom.git ~/spring-base-bom
            - run: mvn -f ~/spring-base-bom clean install
            - attach_workspace:
                  at: ~/spring-mvc-bom
            - run: git clone https://github.com/amit-agrawal10-git/spring-mvc-bom.git ~/spring-mvc-bom
            - run: mvn -f ~/spring-mvc-bom clean install
            - attach_workspace:
                  at: ~/amag-platform
            - run: git clone https://github.com/amit-agrawal10-git/amag-platform.git ~/amag-platform
            - run: mvn -f ~/amag-platform clean install
            - run: mvn dependency:go-offline

            # run tests!
            - run: mvn integration-test